name: Push docker image | Production
  
on:
  push:
    branches: [main]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set time
        run: |
          echo "date="$(date +"%Y-%m-%d")"" >> $GITHUB_ENV

      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build image
        run: docker build -t smallbrains .

      - name: Push image
        run: |
          docker tag smallbrains ${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/production:${{ env.date }}

          docker push ${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/production:${{ env.date }}